<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="test1"
           tests="4"
           failures="1"
           errors="0"
           skipped="2"
           time="37.950">
  <properties />
            <testcase name="loginTest" time="13.799" classname="com.chandao.testcase.LoginTest">
                <failure type="junit.framework.AssertionFailedError"
                  message="查找元素异常，退出当前测试用例"
              >
<![CDATA[junit.framework.AssertionFailedError: 查找元素异常，退出当前测试用例
  junit.framework.Assert.fail(Assert.java:47)
  com.chandao.baseframework.WebElementUntils.getElement(WebElementUntils.java:57)
  com.chandao.baseframework.WebElementUntils$1.apply(WebElementUntils.java:66)
  com.chandao.baseframework.WebElementUntils$1.apply(WebElementUntils.java:1)
  org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:209)
  com.chandao.baseframework.WebElementUntils.findElement(WebElementUntils.java:64)
  com.chandao.baseframework.WebElementUntils.sendkeys(WebElementUntils.java:79)
  com.chandao.pages.LoginPage.inputUserName(LoginPage.java:30)
  com.chandao.actions.LoginOperate.LoginSuess(LoginOperate.java:25)
  com.chandao.actions.LoginOperate.getLoginName(LoginOperate.java:31)
  com.chandao.testcase.LoginTest.loginTest(LoginTest.java:46)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:498)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
  org.testng.internal.Invoker.retryFailed(Invoker.java:998)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1200)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
  org.testng.TestRunner.privateRun(TestRunner.java:756)
  org.testng.TestRunner.run(TestRunner.java:610)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
  org.testng.SuiteRunner.run(SuiteRunner.java:289)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
  org.testng.TestNG.runSuites(TestNG.java:1133)
  org.testng.TestNG.run(TestNG.java:1104)
  org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
      </failure>

          </testcase>
  
            <testcase name="loginTest" time="0.0" classname="com.chandao.testcase.LoginTest">
          <skipped />
    </testcase>
            <testcase name="loginTest" time="0.0" classname="com.chandao.testcase.LoginTest">
          <skipped />
    </testcase>
  
            <testcase name="filelogin01" time="2.721" classname="com.chandao.testcase.LoginTest" />
      
</testsuite>
